version: "3.8"

services:

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -ui -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1"
    volumes:
      - ./consul:/consul/data
    networks:
      - network

  rate_limiter_service:
    image: rate_limiter_service
    container_name: rate_limiter_service
    hostname: rate_limiter_service
    build:
      context: ./rate-limiter-service/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - consul
    environment:
      DB: ${DB}
      DBPORT: ${DBPORT}
    networks:
      - network
    ports:
      - "8090:8090"
      - "8080:8080"

networks:
  network:
    driver: bridge
